### ISSUE TITLE
GH installation fail -- Unicode Decode Error

### ISSUE THREAD

**Issue by charleygros** [scikit-maad/scikit-maad#38]
Hi there,

Trying to install your repository on my Windows 10.

Did the following:
```
git clone https://github.com/scikit-maad/scikit-maad.git --branch 1.3
```

Got:
```
Cloning into 'scikit-maad'...
remote: Enumerating objects: 9275, done.
remote: Counting objects: 100% (1885/1885), done.
remote: Compressing objects: 100% (996/996), done.
remote: Total 9275 (delta 1350), reused 1366 (delta 868), pack-reused 7390
Receiving objects: 100% (9275/9275), 170.35 MiB | 10.14 MiB/s, done.
Resolving deltas: 100% (6865/6865), done.
Note: switching to 'e883cb8eea54463190a4b1f78872c9121a75bb8b'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Updating files: 100% (335/335), done.
```

Then did:
```
cd scikit-maad/
python setup.py install
```

Got:
```
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    long_description = fdesc.read()
  File "C:\Users\cgros\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1804: character maps to <undefined>
```

Could you please help me? Many thanks in advance

**Comment by charleygros** [comment]
(PS: all g w `pip install` tho)

**Comment by shaupert** [comment]
Hi Charleygros,

I suggest to use the `pip install` command : `pip install scikit-maad==1.3` to install the version 1.3, or simply scikit-maad to install the lastest version (which is currently 1.3 :)) 
Sylvain

**Comment by charleygros** [comment]
> I suggest to use the `pip install` command : `pip install scikit-maad==1.3` to install the version 1.3, or simply scikit-maad to install the lastest version (which is currently 1.3 :))

Works great on my hand. Cheers
