### ISSUE TITLE
AttributeError: 'AxesImage' object has no property 'fcrop'

### ISSUE THREAD

**Issue by Bengt** [scikit-maad/scikit-maad#61]
I run this code from the documentation:

```python
import maad

s, fs = maad.sound.load_url('cold_forest_daylight')
Sxx, tn, fn, ext = \
    maad.sound.spectrogram(s, fs, fcrop=(0,20000), display=True)
Sxx_dB = maad.util.power2dB(Sxx) + 96
Sxx_dB_blurred = maad.sound.smooth(Sxx_dB)
im_bin = \
    maad.rois.create_mask(
        Sxx_dB_blurred, bin_std=1.5, bin_per=0.5, mode='relative'
    )
im_rois, df_rois = maad.rois.select_rois(im_bin, display=True)
Sxx_noNoise = maad.sound.median_equalizer(Sxx)
Sxx_noNoise_dB = maad.util.power2dB(Sxx_noNoise)
Sxx_noNoise_dB_blurred = maad.sound.smooth(Sxx_noNoise_dB)
im_bin2 = maad.rois.create_mask(
    Sxx_noNoise_dB_blurred, bin_std=6, bin_per=0.5, mode='relative'
)
im_rois2, df_rois2 = maad.rois.select_rois(im_bin2, display=True)
```

I get this error:

```bash
/Users/bengt/Downloads/_Bengts/git.ni.dfki.de/IML/CST/CST.Maad-Dash/venv/bin/python /Users/bengt/Downloads/_Bengts/git.ni.dfki.de/IML/CST/CST.Maad-Dash/maad_dash/select_rois_demo.py 
Traceback (most recent call last):
  File "/Users/bengt/Downloads/_Bengts/git.ni.dfki.de/IML/CST/CST.Maad-Dash/maad_dash/select_rois_demo.py", line 5, in <module>
    maad.sound.spectrogram(s, fs, fcrop=(0,20000), display=True)
  File "/Users/bengt/Downloads/_Bengts/git.ni.dfki.de/IML/CST/CST.Maad-Dash/venv/lib/python3.10/site-packages/maad/sound/spectro_func.py", line 286, in spectrogram
    _, fig = plot2d(Sxx_disp, extent=extent, figsize=figsize, title=title,
  File "/Users/bengt/Downloads/_Bengts/git.ni.dfki.de/IML/CST/CST.Maad-Dash/venv/lib/python3.10/site-packages/maad/util/visualization.py", line 934, in plot2d
    _im = ax.imshow(im, extent=extent, origin="lower", cmap=cmap, 
  File "/Users/bengt/Downloads/_Bengts/git.ni.dfki.de/IML/CST/CST.Maad-Dash/venv/lib/python3.10/site-packages/matplotlib/__init__.py", line 1431, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/bengt/Downloads/_Bengts/git.ni.dfki.de/IML/CST/CST.Maad-Dash/venv/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 5515, in imshow
    im = mimage.AxesImage(self, cmap, norm, interpolation, origin, extent,
  File "/Users/bengt/Downloads/_Bengts/git.ni.dfki.de/IML/CST/CST.Maad-Dash/venv/lib/python3.10/site-packages/matplotlib/image.py", line 897, in __init__
    super().__init__(
  File "/Users/bengt/Downloads/_Bengts/git.ni.dfki.de/IML/CST/CST.Maad-Dash/venv/lib/python3.10/site-packages/matplotlib/image.py", line 257, in __init__
    self.update(kwargs)
  File "/Users/bengt/Downloads/_Bengts/git.ni.dfki.de/IML/CST/CST.Maad-Dash/venv/lib/python3.10/site-packages/matplotlib/artist.py", line 996, in update
    raise AttributeError(f"{type(self).__name__!r} object "
AttributeError: 'AxesImage' object has no property 'fcrop'
```

My environment looks like this:

```txtcertifi==2022.12.7
cycler==0.11.0
imageio==2.25.0
kiwisolver==1.4.4
llvmlite==0.39.1
matplotlib==3.3.0
networkx==3.0
numba==0.56.4
numpy==1.23.5
packaging==23.0
pandas==1.5.3
Pillow==9.4.0
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.7.1
PyWavelets==1.4.1
resampy==0.2.2
scikit-image==0.19.3
scikit-maad==1.3.12
scipy==1.10.0
six==1.16.0
tifffile==2023.2.3
tqdm==4.64.1
```

This is under macOS an Apple Silicone.

**Comment by Bengt** [comment]
Source: <https://scikit-maad.github.io/generated/maad.rois.select_rois.html>

**Comment by shaupert** [comment]
Thanks to point out the bug.
We forgot to change the argument `fcrop` in the function spectrogram
We fixed the bug by replacing `fcrop` by `flims`
