### ISSUE TITLE
Make matplotlib an optional dependency

### ISSUE THREAD

**Issue by Bengt** [scikit-maad/scikit-maad#73]
Currently, matplotlib is tightly coupled to this library because many modules import it. In case one uses another plotting library, the matplotlib requirement should be optional. This would decrease the disk space required for installation and also save on memory at runtime.

**Comment by Bengt** [comment]
When I try uninstalling matplotlib from my environment, I get errors like this:

``
Traceback (most recent call last):
  File "/app/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/app/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/app/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/app/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/app/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/app/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/app/venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/maad_dash/app/main.py", line 25, in <module>
    from maad_dash.app.spectrogram_figure_getting import get_spectrogram_figure
  File "/app/maad_dash/app/spectrogram_figure_getting.py", line 1, in <module>
    from maad.sound import load
  File "/app/venv/lib/python3.10/site-packages/maad/__init__.py", line 32, in <module>
    from . import features
  File "/app/venv/lib/python3.10/site-packages/maad/features/__init__.py", line 72, in <module>
    from .shape import (filter_multires,
  File "/app/venv/lib/python3.10/site-packages/maad/features/shape.py", line 23, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
```

**Comment by shaupert** [comment]
Hi @Bengt , you're right maad is tightly coupled with matplotlib. This is on purpose as we wanted to provide an easy way to plot results, especially for novices in Python. We don't plan to get rid of matplotlib :)

**Comment by Bengt** [comment]
Hi, Sylvain! Thanks for clarifying. I see that my use case of building another (Dash-based) frontend is just out of scope for this project then.
